#nullable disable
using AppCore.Results.Bases;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

//Generated by ScaffoldApp.
namespace MVC.Controllers
{
    public class BlogsController : Controller
    {
        // Add service injections here
        private readonly IBlogService _blogService;
        private readonly IUserService _userService;
        private readonly ITagService _tagService;

        public BlogsController(IBlogService blogService, IUserService userService, ITagService tagService)
        {
            _blogService = blogService;
            _userService = userService;
            _tagService = tagService;
        }

        // GET: Blogs
        public IActionResult Index()
        {
            List<BlogModel> blogList = _blogService.Query().ToList();
            return View(blogList);
        }

        public IActionResult IndexJSon()
        {
            var blogList = _blogService.Query().ToList();
            return Json(blogList);
        }

        // GET: Blogs/Details/5
        public IActionResult Details(int id)
        {
            BlogModel blog = _blogService.Query().SingleOrDefault(b => b.Id == id); // TODO: Add get item service logic here
            if (blog == null)
            {
                return View("_Error", "Blog not found!");
            }
            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "UserName");
            ViewBag.Tags = new MultiSelectList(_tagService.Query().ToList(), "Id", "Name");
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BlogModel blog)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add insert service logic here
                Result result = _blogService.Add(blog);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
					return RedirectToAction(nameof(Index));
				}
                //ViewBag.CreateMessage = result.Message;
                ModelState.AddModelError("", result.Message);
            }
			// Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
			ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "UserName");
			ViewBag.Tags = new MultiSelectList(_tagService.Query().ToList(), "Id", "Name");
			return View(blog);
        }

        // GET: Blogs/Edit/5
        public IActionResult Edit(int id)
        {
            BlogModel blog = _blogService.Query().SingleOrDefault(b => b.Id == id); // TODO: Add get item service logic here
            if (blog == null)
            {
                return View("_Error", "Blog not found!");
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "UserName", blog.UserId);
            ViewData["Tags"] = new MultiSelectList(_tagService.GetList(), "Id", "Name", blog.TagIds);
            return View(blog);
        }

        // POST: Blogs/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BlogModel blog)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                var result = _blogService.Update(blog);
                if (result.IsSuccessful)
                {
					TempData["Message"] = result.Message;
					return RedirectToAction(nameof(Index));
				}
				ModelState.AddModelError("", result.Message);
			}
			// Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
			ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "UserName", blog.UserId);
			ViewData["Tags"] = new MultiSelectList(_tagService.GetList(), "Id", "Name", blog.TagIds);
			return View(blog);
        }

		// GET: Blogs/Delete/5
		public IActionResult Delete(int id)
		{
			var result = _blogService.Delete(id);
			TempData["Message"] = result.Message;
			return RedirectToAction(nameof(Index));
		}
	}
}
